server:
  port: 8999
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: catalogModule
          uri: lb://catalog-service
          predicates:
            - Path=/products/**
        - id: userModule
          uri: lb://user-service
          predicates:
            - Path=/users/**,/auth/**
        - id: orderModule
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: paymentModule
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: cartModule
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'

