server:
  port: 8999
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: productModule
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: userModule
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: orderModule
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: paymentModule
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'

