spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3308/db
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
