server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:///C:\Users\andre\IdeaProjects\application-config
          searchPaths: '{application}/{profile}'