server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/neaguandrei/application-config
          search-paths: '{application}/{profile}'
